### ISSUE TITLE
not connecting

### ISSUE THREAD

**Issue by rattan28** [D-storm/GTU-Student-Attendance-System#9]
Error: SQLSTATE [HY000] [1045] Access denied for user: 'admin' @ '@ localhost' (password: YES)
what is the solution
thanks

**Comment by D-storm** [comment]
1. Did you configured the username and password in 'core/config/db/credentials.db.php' correctly to match what you have in MySQL database?
2. Check if the MySQL user you have configured has full permissions on attendance management system database.
